version: '3.8'
services:
  producer:
    build: .
    command: python producer.py
    depends_on:
      - rabbitmq
      - redis
      - db

  consumer:
    build: .
    command: python consumer.py
    depends_on:
      - rabbitmq
      - redis
      - db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: review_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
